In [3]:
import numpy as np

In [9]:
arr = np.array([1,2,3])

In [10]:
print(type(arr))

<class 'numpy.ndarray'>


In [12]:
# ndarray => n dimentional array
arr = np.array([[1,2,3], [4,5,6]])

In [13]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [15]:
# bagaimana kita mengakses arr
# 1. cara biasa seperti list
print(arr[0])
print(arr[0, 2])

[1 2 3]
3


In [16]:
# 1 dimensi array
arr = np.array([1,2,3,4,5,6])

In [19]:
# 2. cara masking
mask = np.array([True, True, False, False, False, True])
print(arr[mask])

[1 2 6]


In [23]:
# 3. mengeluarkan multi index
idxs = np.array([2, 5, -1])
print(arr[idxs])

[3 6 6]


In [33]:
# Terminology dan Methods
arr = np.array([[1,2,3], [4,5,6]])
print(arr.max(axis=1))

[3 6]


In [36]:
# print dimensi
print(arr.ndim)
arr = np.array([[[1,2,3],[1,2,3],[1,2,3], [1,2,3]], [[4,5,6],[4,5,6],[4,5,6], [4,5,6]]])
print(arr.ndim)

3
3


In [37]:
# print ukuran dari array
print(arr.shape)

(2, 4, 3)


In [41]:
arr_str = np.array(["a"])
print(arr_str)

['a']


In [55]:
# Membuat Array
# 1. menggunakan np.array
arr = np.array([])
# 2. zero array
arr_zero = np.zeros(1)
# 3. array one
arr_one = np.ones(1)
# 4. empty
arr_empty = np.empty((4,4))
# 5. arange [start], stop, [step]
arr_range = np.arange(0, 10, 1)

In [54]:
print(arr, arr_zero, arr_one, arr_empty, arr_range)

[] [0.] [1.] [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] [0 1 2 3 4 5 6 7 8 9]


In [62]:
# Methods numpy bukan punya ndarray
print(np.append(arr, [1,2,3]))
print(np.delete(arr_range, [1, 2, 3, 4]))
print(np.sort(arr_range, ))

# DOCUMENTATION: https://numpy.org/doc/stable/reference/index.html

[1. 2. 3.]
[0 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [66]:
# reshape => mengubah dimensi array
arr = np.arange(0, 32, 1)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]


In [67]:
print(arr.size)

32


In [150]:
arr.reshape((8, 4))
# untuk menghindari unbalance array size
# kita bisa menggunakan data cleansing

ValueError: cannot reshape array of size 3 into shape (8,4)

In [71]:
arr.reshape((8, 2, 2))

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31]]])

In [72]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]


In [73]:
np.reshape(arr, (8,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [74]:
# Converting Array Dimension
arr.reshape((32, 1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31]])

In [78]:
print(np.newaxis)
arr_2d = arr[:, np.newaxis]
print(arr_2d)

None
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]
 [31]]


In [79]:
arr_2d = arr[np.newaxis, :]
print(arr_2d)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31]]


In [83]:
# Indexing and Slicing
# sifat yang sama dengan list => kita bisa slice
arr = np.arange(0, 5, 1)
print(arr[0:3])
print(arr[:6])
print(arr[3:])
print(arr[-2:])

[0 1 2]
[0 1 2 3 4]
[3 4]
[3 4]


In [85]:
arr = np.arange(0, 100, 1)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [89]:
print(arr[arr % 3 == 0])
print(arr % 3 == 0)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]
[ True False False  True False False  True False False  True False False
  True False False  True False False  True False False  True False False
  True False False  True False False  True False False  True False False
  True False False  True False False  True False False  True False False
  True False False  True False False  True False False  True False False
  True False False  True False False  True False False  True False False
  True False False  True False False  True False False  True False False
  True False False  True False False  True False False  True False False
  True False False  True]


In [92]:
# tidak bisa dilakukan hal diatas pada list
list = [1,2,3]
print(list)
print(list % 3)

[1, 2, 3]


TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [102]:
# Stacking Array
arr1 = np.arange(0, 5, 1)
arr2 = np.arange(5, 10, 1)
print(arr1, arr2)

[0 1 2 3 4] [5 6 7 8 9]


In [103]:
np.vstack((arr1, arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [104]:
np.hstack((arr1, arr2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
arr3 = np.vstack((arr1, arr2))
arr3_splitted = np.vsplit(arr3, 2)
arr3_splitted[0].size

5

In [111]:
# Mutable dan Immutable
# array itu mutable
arr = np.array([1,2,3])
arr2 = arr.view()
arr2[0] = 4
print(arr, arr2)

[4 2 3] [4 2 3]


In [112]:
# Shallow and Deep Copy
arr = np.array([1,2,3])
arr2 = arr.copy()
arr2[0] = 4
print(arr, arr2)

[1 2 3] [4 2 3]


In [113]:
# Operasi matematika untuk array

# penambahan
print(arr + arr2)

[5 4 6]


In [114]:
# perkalian
print(arr * arr2)

[4 4 9]


In [115]:
# modulo
print(arr % arr2)

[1 0 0]


In [116]:
arr_2d = np.vstack((arr, arr2))
arr_2d_2 = np.vstack((arr2, arr))

In [117]:
print(arr_2d + arr_2d_2)

[[5 4 6]
 [5 4 6]]


In [118]:
np.sqrt(arr_2d)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 1.41421356, 1.73205081]])

In [119]:
np.square(arr_2d)

array([[ 1,  4,  9],
       [16,  4,  9]])

In [120]:
# Broadcasting
# operasi array dengan skalar
print(arr_2d *  10)

[[10 20 30]
 [40 20 30]]


In [122]:
print(arr_2d  % 2)

[[1 0 1]
 [0 0 1]]


In [123]:
print(arr, arr_2d)

[1 2 3] [[1 2 3]
 [4 2 3]]


In [125]:
print(arr_2d + arr)

[[2 4 6]
 [5 4 6]]


In [126]:
print(arr_2d.max())

4


In [127]:
print(arr_2d.min())

1


In [130]:
print(arr_2d.sum())
print(arr_2d.sum(axis=0))
print(arr_2d.sum(axis=1))

15
[5 4 6]
[6 9]


In [131]:
print(arr_2d.mean())

2.5


In [132]:
print(arr_2d.std())

0.9574271077563381


In [133]:
print(arr_2d.prod())

144


In [ ]:
# Arr numpy == Matrix

In [141]:
mat1 = np.random.random((3,3))
mat2 = np.random.random((3,3))

In [142]:
print(mat1, mat2)

[[0.03174013 0.38610671 0.05213139]
 [0.86279876 0.51919653 0.99420762]
 [0.51779224 0.62749909 0.52782364]] [[0.26760102 0.30576203 0.9820428 ]
 [0.22361293 0.35681115 0.19821205]
 [0.64805984 0.83249029 0.11090114]]


In [143]:
# operasi matrix
print(mat1 + mat2)
print(mat1 * mat2)
print(mat1 / mat2)
print(mat1 % mat2)

[[0.29934115 0.69186874 1.03417419]
 [1.08641168 0.87600768 1.19241967]
 [1.16585208 1.45998938 0.63872478]]
[[0.00849369 0.11805677 0.05119525]
 [0.19293296 0.18525511 0.19706393]
 [0.33556035 0.5223869  0.05853624]]
[[0.1186099  1.26276864 0.05308464]
 [3.85844758 1.45510175 5.01587883]
 [0.79898831 0.75376145 4.75940693]]
[[0.03174013 0.08034467 0.05213139]
 [0.19195998 0.16238538 0.00314738]
 [0.51779224 0.62749909 0.08421909]]


In [145]:
# slicing matrix
mat1[0, 2]

0.05213138707643994

In [147]:
mat1[:1]

array([[0.03174013, 0.38610671, 0.05213139]])

In [149]:
# dot product from 2 matrix
dot_product= np.dot(mat1, mat2)
print(dot_product)

[[0.1286164  0.19087098 0.1134826 ]
 [0.99129091 1.2767344  1.06047507]
 [0.62093994 0.82162793 0.69140826]]


In [151]:
mat1

array([[0.03174013, 0.38610671, 0.05213139],
       [0.86279876, 0.51919653, 0.99420762],
       [0.51779224, 0.62749909, 0.52782364]])

In [153]:
mat1_T = mat1.T
mat1_T

array([[0.03174013, 0.86279876, 0.51779224],
       [0.38610671, 0.51919653, 0.62749909],
       [0.05213139, 0.99420762, 0.52782364]])

In [156]:
np.cross(mat1, mat1_T)

array([[ 0.15494416, -0.01478014,  0.01513027],
       [-0.1903938 , -0.15753521,  0.24749686],
       [-0.19355743, -0.24578681,  0.48208059]])

In [157]:
mat1

array([[0.03174013, 0.38610671, 0.05213139],
       [0.86279876, 0.51919653, 0.99420762],
       [0.51779224, 0.62749909, 0.52782364]])

In [164]:
mat1_f = mat1.flatten()
mat1_f[0] = 100
mat1_f

array([1.00000000e+02, 3.86106706e-01, 5.21313871e-02, 8.62798757e-01,
       5.19196528e-01, 9.94207619e-01, 5.17792237e-01, 6.27499090e-01,
       5.27823640e-01])

In [165]:
mat1

array([[0.03174013, 0.38610671, 0.05213139],
       [0.86279876, 0.51919653, 0.99420762],
       [0.51779224, 0.62749909, 0.52782364]])

In [166]:
mat1_f = mat1.ravel()
mat1_f[0] = 100
mat1_f

array([1.00000000e+02, 3.86106706e-01, 5.21313871e-02, 8.62798757e-01,
       5.19196528e-01, 9.94207619e-01, 5.17792237e-01, 6.27499090e-01,
       5.27823640e-01])

In [167]:
mat1

array([[1.00000000e+02, 3.86106706e-01, 5.21313871e-02],
       [8.62798757e-01, 5.19196528e-01, 9.94207619e-01],
       [5.17792237e-01, 6.27499090e-01, 5.27823640e-01]])

In [169]:
# inverse matrix
inv1 = np.linalg.inv(mat1) 

In [172]:
np.dot(mat1, inv1)

array([[ 1.00000000e+00,  9.16269469e-17,  1.23411338e-16],
       [-1.38679662e-18,  1.00000000e+00, -4.82825933e-17],
       [-4.84313486e-19,  4.15455866e-17,  1.00000000e+00]])